package:
    name: lpsolve55
    version: 5.5

source:
    fn: lp_solve_5.5.2.5_Python_source.tar.gz
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.5/lp_solve_5.5.2.5_Python_source.tar.gz
    md5: 937f97a6e236e6ddc095485673a7a9ce

    patches:
        - setup.patch # [unix]
        - setup_win.patch # [win]
        - hash_osx.patch # [osx]

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - lpsolve
        - cmake
    run:
        - python
        - numpy
        - lpsolve

test:
    imports:
        - lpsolve55

about:
    home: http://lpsolve.sourceforge.net/
    license: LGPL
    summary: "Linear Program Solver, Python Interface to lpsolve"
