package:
  name: mopac
  version: 2012

source:
  fn: MOPAC2012_for_Macintosh.zip # [osx]
  url: http://openmopac.net/MOPAC2012_for_Macintosh.zip # [osx]
  md5: 2bd2f292f08f05a4ef9f9f9a45bc0df4 # [osx]
  
  fn: MOPAC2012_for_Linux_64_bit.zip # [linux64]
  url: http://openmopac.net/MOPAC2012_for_Linux_64_bit.zip # [linux64]
  md5: d5909a8cee3f8d4b174a728611226861 # [linux64]

  fn: MOPAC2012_for_Linux_32_bit.zip # [linux32]
  url: http://openmopac.net/MOPAC2012_for_Linux_32_bit.zip # [linux32]
  md5: 15273d86b86d2e4cbbb5e493340d881d # [linux32]

  
  
build:
  number: 2
  binary_relocation: false

test:
  commands:
    - mopac

about:
  home: http://openmopac.net
  license: executables are available FREE for academic, not-for-profit use