package:
  name: scoop
  version: "0.7"

source:
  git_url: https://github.com/soravux/scoop.git

requirements:
  build:
    - greenlet
    - pyzmq
    - python
    - setuptools

  run:
    - greenlet
    - pyzmq
    - python

test:
  imports:
    - scoop

  commands:
    - cd $SRC_DIR/test ; python -m scoop tests_parser.py
    - cd $SRC_DIR/test ; python -m scoop tests_stat.py
    - cd $SRC_DIR/test ; python -m scoop tests_stopwatch.py

about:
  home: https://github.com/soravux/scoop.git
  license: GNU LESSER GENERAL PUBLIC LICENSE
  summary: 'Scalable COncurrent Operations in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
